# SPDX-License-Identifier: MIT
"""Top-level ``logion completion`` command.

Prints a shell tab-completion script for the whole CLI. The script is
generated by introspecting the live ``build_parser()`` argparse tree via
`shtab`, so every command, subcommand, and flag is covered automatically
and stays in sync as the parser evolves — there is no hand-maintained
list to drift.

Usage (per shell)::

    # bash — one-shot for the current session
    eval "$(logion completion bash)"
    # bash — persist
    logion completion bash > ~/.local/share/bash-completion/completions/logion

    # zsh — persist to a directory on your $fpath
    logion completion zsh > ~/.zfunc/_logion

    # tcsh
    logion completion tcsh > ~/.config/logion/completion.tcsh
"""

from __future__ import annotations

import argparse

from cli._errors import emit_error_json, print_err
from cli._options import COMMON_PARSER
from cli._output import emit_json

_KIND = "logion.completion"
_SHELLS = ("bash", "zsh", "tcsh")


def handle_completion(args: argparse.Namespace) -> int:
    """Emit a shell completion script for the requested shell."""
    try:
        import shtab
    except ImportError:  # pragma: no cover - shtab is a hard dependency
        message = (
            "shtab is required to generate completion scripts but is not "
            "installed. Reinstall the logion CLI to pull it in."
        )
        if getattr(args, "json_output", False):
            emit_error_json("shtab_missing", message, 1)
        else:
            print_err(message)
        return 1

    # Build a fresh parser so the completion reflects the full command
    # tree, independent of how this invocation was parsed.
    from cli._parser import build_parser

    parser = build_parser()
    # nosec B604: shtab's ``shell`` is the target shell *name* (one of a
    # fixed choices list), not a subprocess ``shell=True`` — no shell is
    # spawned and no user string is interpolated into a command.
    script = shtab.complete(parser, shell=args.shell)  # nosec B604

    if getattr(args, "json_output", False):
        emit_json(_KIND, {"shell": args.shell, "script": script})
    else:
        # ``script`` already ends with its own trailing newline.
        print(script, end="" if script.endswith("\n") else "\n")
    return 0


def register(subparsers: argparse._SubParsersAction) -> None:
    """Register the ``completion`` command."""
    parser = subparsers.add_parser(
        "completion",
        help="Print a shell tab-completion script for the logion CLI",
        parents=[COMMON_PARSER],
    )
    parser.add_argument(
        "shell",
        choices=_SHELLS,
        help="Shell to generate a completion script for.",
    )
    parser.set_defaults(handler=handle_completion)
