# SPDX-License-Identifier: MIT
"""Static keyword mappings for deterministic taxonomy suggestions.

Kept separate from the suggestion logic to respect the CLI architecture
source-file size limit.
"""

from __future__ import annotations

# Deterministic keyword → category mapping. Order matters only for
# readability; each keyword set is disjoint in practice.
CATEGORY_KEYWORDS: dict[str, frozenset[str]] = {
    "automation": frozenset({
        "automation",
        "automate",
        "workflow",
        "pipeline",
        "ci",
        "cd",
    }),
    "code-review": frozenset({
        "review",
        "pr",
        "pull-request",
        "lint",
        "linter",
        "code-review",
    }),
    "data": frozenset({
        "data",
        "dataset",
        "database",
        "sql",
        "etl",
        "warehouse",
    }),
    "devops": frozenset({
        "devops",
        "terraform",
        "kubernetes",
        "docker",
        "helm",
        "deploy",
    }),
    "documentation": frozenset({
        "docs",
        "documentation",
        "readme",
        "manual",
        "guide",
    }),
    "finance": frozenset({
        "finance",
        "accounting",
        "invoice",
        "ledger",
        "payment",
    }),
    "marketing": frozenset({
        "marketing",
        "seo",
        "campaign",
        "email",
        "newsletter",
    }),
    "media": frozenset({
        "video",
        "audio",
        "image",
        "media",
        "transcode",
        "editing",
    }),
    "productivity": frozenset({
        "productivity",
        "task",
        "todo",
        "notes",
        "calendar",
        "schedule",
    }),
    "research": frozenset({
        "research",
        "analysis",
        "survey",
        "study",
        "literature",
    }),
    "security": frozenset({
        "security",
        "vulnerability",
        "cve",
        "pentest",
        "audit",
    }),
    "testing": frozenset({
        "test",
        "testing",
        "qa",
        "unit-test",
        "integration-test",
        "pytest",
    }),
    "writing": frozenset({
        "writing",
        "blog",
        "article",
        "content",
        "copy",
        "prose",
    }),
}

# Words that appear frequently but carry no taxonomy signal.
STOP_WORDS: frozenset[str] = frozenset({
    "the",
    "and",
    "for",
    "with",
    "your",
    "this",
    "that",
    "from",
    "into",
    "using",
    "use",
    "can",
    "will",
    "you",
    "are",
    "not",
    "but",
    "how",
    "what",
    "when",
    "who",
    "all",
    "new",
    "one",
    "two",
    "get",
    "set",
    "run",
    "make",
    "via",
    "out",
    "our",
    "own",
    "any",
    "has",
    "had",
    "was",
    "were",
    "been",
    "have",
    "they",
    "them",
    "their",
    "there",
    "here",
    "some",
    "such",
    "than",
    "then",
    "also",
    "only",
    "just",
    "like",
    "able",
    "over",
    "more",
    "most",
})
