# SPDX-License-Identifier: MIT
"""Handlers for ``courses capabilities`` sub-commands."""

from __future__ import annotations

import argparse
import json
import sys
from importlib import resources
from pathlib import Path
from typing import Any

import yaml

from cli._config import resolve_config_from_args
from cli._course_capabilities import (
    CAPABILITY_MANIFEST_PATH,
    CapabilityManifestError,
    load_and_validate_capability_manifest,
    summarize_capability_manifest,
)
from cli._output import emit_json
from cli.commands.courses._capability_render import (
    _append_summary_fields,
)
from cli.commands.courses.capability_frontmatter import (
    extract_logion_capabilities_from_skill,
)

CAPABILITIES_TEMPLATE_FILENAME = "course_capabilities.template.yaml"


def handle_courses_capabilities_validate(
    args: argparse.Namespace,
) -> int:
    """Validate a local capability manifest and print a summary."""
    try:
        manifest = load_and_validate_capability_manifest(args.bundle_dir)
    except CapabilityManifestError as exc:
        print(f"Invalid capability manifest: {exc}", file=sys.stderr)
        return 2
    config = resolve_config_from_args(args)
    summary = summarize_capability_manifest(manifest)
    if config.json_output:
        payload = {"capabilities_status": "declared", **summary}
        emit_json("logion.courses.capabilities.validate", payload)
    else:
        lines = ["capabilities_status: declared"]
        _append_summary_fields(lines, summary)
        print("\n".join(lines))
    return 0


def handle_courses_capabilities_print(
    args: argparse.Namespace,
) -> int:
    """Validate a local capability manifest and print normalised JSON."""
    try:
        manifest = load_and_validate_capability_manifest(args.bundle_dir)
    except CapabilityManifestError as exc:
        print(f"Invalid capability manifest: {exc}", file=sys.stderr)
        return 2
    config = resolve_config_from_args(args)
    if config.json_output:
        emit_json("logion.courses.capabilities.print", manifest)
    else:
        print(json.dumps(manifest, indent=2, sort_keys=True))
    return 0


def _template_text() -> str:
    """Return the bundled capability manifest scaffold contents."""
    return (
        resources
        .files("cli.templates")
        .joinpath(CAPABILITIES_TEMPLATE_FILENAME)
        .read_text(encoding="utf-8")
    )


def _serialize_manifest_yaml(manifest: dict[str, Any]) -> str:
    """Serialise a normalised manifest dict to YAML with a header."""
    body = yaml.safe_dump(
        manifest,
        default_flow_style=False,
        sort_keys=True,
        allow_unicode=True,
        width=88,
    )
    header = (
        "# course/capabilities.yaml — generated from SKILL.md\n"
        "#\n"
        "# Generated by `logion courses capabilities scaffold --from-skill`.\n"
        "# Review every field before publishing. This file is the canonical\n"
        "# publication contract — SKILL.md frontmatter is only a seed.\n"
        "\n"
    )
    return header + body


def _scaffold_from_skill(
    skill_path: Path,
    bundle_dir: Path | None,
    force: bool,
) -> int:
    """Seed a capability manifest from SKILL.md frontmatter.

    When *bundle_dir* is None the serialised manifest is printed to stdout.
    Otherwise it is written to ``<bundle-dir>/course/capabilities.yaml``
    with overwrite protection unless *force* is True.
    """
    try:
        manifest = extract_logion_capabilities_from_skill(skill_path)
    except CapabilityManifestError as exc:
        print(f"Error reading SKILL.md: {exc}", file=sys.stderr)
        return 2
    if manifest is None:
        print(
            "SKILL.md has no metadata.logion capability manifest",
            file=sys.stderr,
        )
        return 2
    text = _serialize_manifest_yaml(manifest)
    if bundle_dir is None:
        print(text, end="")
        return 0
    dest = bundle_dir / CAPABILITY_MANIFEST_PATH
    if dest.exists() and not force:
        print(
            f"Refusing to overwrite existing manifest: {dest} "
            "(pass --force to replace)",
            file=sys.stderr,
        )
        return 2
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(text, encoding="utf-8")
    print(f"Wrote scaffold to {dest}")
    return 0


def _scaffold_template(
    bundle_dir: Path | None,
    force: bool,
) -> int:
    """Emit the generic commented template scaffold."""
    text = _template_text()
    if bundle_dir is None:
        print(text, end="")
        return 0
    dest = bundle_dir / CAPABILITY_MANIFEST_PATH
    if dest.exists() and not force:
        print(
            f"Refusing to overwrite existing manifest: {dest} "
            "(pass --force to replace)",
            file=sys.stderr,
        )
        return 2
    dest.parent.mkdir(parents=True, exist_ok=True)
    # Write the already-loaded text directly.  ``resources.files()``
    # returns a Traversable that may not have a stable on-disk path
    # (e.g. zip-installed wheels), so do not round-trip through
    # ``Path(str(...))`` just to call shutil.copyfile.
    dest.write_text(text, encoding="utf-8")
    print(f"Wrote scaffold to {dest}")
    return 0


def handle_courses_capabilities_scaffold(
    args: argparse.Namespace,
) -> int:
    """Emit the capability manifest scaffold.

    With ``--from-skill`` the scaffold is seeded from the
    ``metadata.logion`` capability manifest embedded in the given
    SKILL.md's YAML frontmatter. Without it, the generic commented
    template is emitted instead.

    With ``--bundle-dir`` the scaffold is written to
    ``<bundle-dir>/course/capabilities.yaml`` (refuses to overwrite an
    existing file unless ``--force`` is passed).  Without ``--bundle-dir``
    the scaffold is printed to stdout so the agent can pipe it.
    """
    bundle_dir: Path | None = getattr(args, "bundle_dir", None)
    from_skill: Path | None = getattr(args, "from_skill", None)
    force: bool = getattr(args, "force", False)
    if from_skill is not None:
        return _scaffold_from_skill(from_skill, bundle_dir, force)
    return _scaffold_template(bundle_dir, force)
