# SPDX-License-Identifier: MIT
"""Handlers for ``courses capabilities`` sub-commands."""

from __future__ import annotations

import argparse
import json
import sys
from importlib import resources
from pathlib import Path

import yaml

from cli._config import resolve_config_from_args
from cli._course_bundle import CourseBundleError, validate_course_bundle
from cli._course_capabilities import (
    CAPABILITY_MANIFEST_PATH,
    CapabilityManifestError,
    load_and_validate_capability_manifest,
    summarize_capability_manifest,
)
from cli._json import JsonObject
from cli._output import emit_json
from cli.commands.courses._capability_render import (
    _append_summary_fields,
)
from cli.commands.courses.capability_frontmatter import (
    extract_logion_capabilities_from_skill,
)

CAPABILITIES_TEMPLATE_FILENAME = "course_capabilities.template.yaml"
LICENSE_TEMPLATE_FILES = {
    "mit": "course_license_mit.template.txt",
    "apache-2.0": "course_license_apache-2.0.template.txt",
    "logion-standard-course-v1": (
        "course_license_logion-standard-course-v1.template.txt"
    ),
}


def handle_courses_capabilities_validate(
    args: argparse.Namespace,
) -> int:
    """Validate a local capability manifest and print a summary."""
    try:
        validate_course_bundle(args.bundle_dir)
        manifest = load_and_validate_capability_manifest(args.bundle_dir)
    except CourseBundleError as exc:
        print(f"Invalid course bundle: {exc}", file=sys.stderr)
        return 2
    except CapabilityManifestError as exc:
        print(f"Invalid capability manifest: {exc}", file=sys.stderr)
        return 2
    config = resolve_config_from_args(args)
    summary = summarize_capability_manifest(manifest)
    if config.json_output:
        payload = {"capabilities_status": "declared", **summary}
        emit_json("logion.courses.capabilities.validate", payload)
    else:
        lines = ["capabilities_status: declared"]
        _append_summary_fields(lines, summary)
        print("\n".join(lines))
    return 0


def handle_courses_capabilities_print(
    args: argparse.Namespace,
) -> int:
    """Validate a local capability manifest and print normalised JSON."""
    try:
        validate_course_bundle(args.bundle_dir)
        manifest = load_and_validate_capability_manifest(args.bundle_dir)
    except CourseBundleError as exc:
        print(f"Invalid course bundle: {exc}", file=sys.stderr)
        return 2
    except CapabilityManifestError as exc:
        print(f"Invalid capability manifest: {exc}", file=sys.stderr)
        return 2
    config = resolve_config_from_args(args)
    if config.json_output:
        emit_json("logion.courses.capabilities.print", manifest)
    else:
        print(json.dumps(manifest, indent=2, sort_keys=True))
    return 0


def _template_text() -> str:
    """Return the bundled capability manifest scaffold contents."""
    return (
        resources
        .files("cli.templates")
        .joinpath(CAPABILITIES_TEMPLATE_FILENAME)
        .read_text(encoding="utf-8")
    )


def _license_template_text(template_name: str) -> str:
    """Return the bundled LICENSE scaffold contents."""
    return (
        resources
        .files("cli.templates")
        .joinpath(LICENSE_TEMPLATE_FILES[template_name])
        .read_text(encoding="utf-8")
    )


def _default_license_template(license_template: str | None) -> str:
    """Choose a license template when scaffolding a local bundle."""
    return license_template or "mit"


def _serialize_manifest_yaml(manifest: JsonObject) -> str:
    """Serialise a normalised manifest dict to YAML with a header."""
    body = yaml.safe_dump(
        manifest,
        default_flow_style=False,
        sort_keys=True,
        allow_unicode=True,
        width=88,
    )
    header = (
        "# course/capabilities.yaml — generated from SKILL.md\n"
        "#\n"
        "# Generated by `logion courses capabilities scaffold --from-skill`.\n"
        "# Review every field before publishing. This file is the canonical\n"
        "# publication contract — SKILL.md frontmatter is only a seed.\n"
        "\n"
    )
    return header + body


def _scaffold_from_skill(
    skill_path: Path,
    bundle_dir: Path | None,
    force: bool,
    license_template: str | None,
) -> int:
    """Seed a capability manifest from SKILL.md frontmatter."""
    try:
        manifest = extract_logion_capabilities_from_skill(skill_path)
    except CapabilityManifestError as exc:
        print(f"Error reading SKILL.md: {exc}", file=sys.stderr)
        return 2
    if manifest is None:
        print(
            "SKILL.md has no metadata.logion capability manifest",
            file=sys.stderr,
        )
        return 2
    text = _serialize_manifest_yaml(manifest)
    if bundle_dir is None:
        print(text, end="")
        return 0
    dest = bundle_dir / CAPABILITY_MANIFEST_PATH
    if dest.exists() and not force:
        print(
            f"Refusing to overwrite existing manifest: {dest} "
            "(pass --force to replace)",
            file=sys.stderr,
        )
        return 2
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(text, encoding="utf-8")
    print(f"Wrote scaffold to {dest}")
    return _write_scaffold_license(bundle_dir, license_template, force)


def _write_license_template(
    bundle_dir: Path,
    template_name: str,
    force: bool,
) -> None:
    """Materialise a LICENSE file from the selected template."""
    dest = bundle_dir / "LICENSE"
    if dest.exists() and not force:
        raise FileExistsError(dest)
    dest.write_text(_license_template_text(template_name), encoding="utf-8")


def _write_scaffold_license(
    bundle_dir: Path,
    license_template: str | None,
    force: bool,
) -> int:
    """Write the bundle LICENSE file for scaffold flows."""
    try:
        _write_license_template(
            bundle_dir,
            _default_license_template(license_template),
            force,
        )
    except FileExistsError:
        license_path = bundle_dir / "LICENSE"
        print(
            f"Refusing to overwrite existing license: {license_path} "
            "(pass --force to replace)",
            file=sys.stderr,
        )
        return 2
    print(f"Wrote scaffold to {bundle_dir / 'LICENSE'}")
    return 0


def _scaffold_template(
    bundle_dir: Path | None,
    force: bool,
    license_template: str | None,
) -> int:
    """Emit the generic commented template scaffold."""
    text = _template_text()
    if bundle_dir is None:
        if license_template is not None:
            print("--license-template requires --bundle-dir", file=sys.stderr)
            return 2
        print(text, end="")
        return 0
    dest = bundle_dir / CAPABILITY_MANIFEST_PATH
    if dest.exists() and not force:
        print(
            f"Refusing to overwrite existing manifest: {dest} "
            "(pass --force to replace)",
            file=sys.stderr,
        )
        return 2
    dest.parent.mkdir(parents=True, exist_ok=True)
    # Write the already-loaded text directly.  ``resources.files()``
    # returns a Traversable that may not have a stable on-disk path
    # (e.g. zip-installed wheels), so do not round-trip through
    # ``Path(str(...))`` just to call shutil.copyfile.
    dest.write_text(text, encoding="utf-8")
    print(f"Wrote scaffold to {dest}")
    return _write_scaffold_license(bundle_dir, license_template, force)


def handle_courses_capabilities_scaffold(
    args: argparse.Namespace,
) -> int:
    """Emit the capability manifest scaffold."""
    bundle_dir: Path | None = getattr(args, "bundle_dir", None)
    from_skill: Path | None = getattr(args, "from_skill", None)
    force: bool = getattr(args, "force", False)
    license_template: str | None = getattr(args, "license_template", None)
    if from_skill is not None:
        return _scaffold_from_skill(
            from_skill,
            bundle_dir,
            force,
            license_template,
        )
    return _scaffold_template(bundle_dir, force, license_template)
