#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Helpers for the public-repo dev rig."""

from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DEVRIG_DIR = ROOT / ".devrig"
DEVRIG_ENV = DEVRIG_DIR / "devrig.env"
DEFAULT_PROD_BASE_URL = "https://api.logion.sh"
DEFAULT_MOCK_BASE_URL = "http://127.0.0.1:4010"
COMPANION_SOURCE = ROOT / "packages" / "agent-companion"
HARNESS_MAP = {
    "claude": {
        "binary": "claude",
        "skill_dir": (".claude", "skills"),
    },
    "codex": {
        "binary": "codex",
        "skill_dir": (".codex", "skills"),
    },
    "hermes": {
        "binary": "hermes",
        "skill_dir": (".hermes", "skills"),
    },
    "opencode": {
        "binary": "opencode",
        "skill_dir": (".config", "opencode", "skills"),
    },
}


def _emit(message: str) -> None:
    sys.stdout.write(f"{message}\n")


def _companion_version() -> str:
    text = (COMPANION_SOURCE / "SKILL.md").read_text(encoding="utf-8")
    for line in text.splitlines():
        if line.startswith("version:"):
            return line.split(":", 1)[1].strip()
    return "latest"


def _harness_skill_dir(agent: str) -> Path:
    return Path.home().joinpath(*HARNESS_MAP[agent]["skill_dir"])


def _load_env(path: Path) -> dict[str, str]:
    env: dict[str, str] = {}
    if not path.is_file():
        return env
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("export "):
            line = line[len("export ") :]
        if "=" not in line:
            continue
        key, value = line.split("=", 1)
        env[key] = value.strip().strip('"')
    return env


def cmd_bootstrap(_args: argparse.Namespace) -> int:
    DEVRIG_DIR.mkdir(parents=True, exist_ok=True)
    _emit(f"Prepared {DEVRIG_DIR}")
    _emit("Next: make dev-up MODE=mock   or   make dev-up MODE=prod")
    return 0


def cmd_env(args: argparse.Namespace) -> int:
    DEVRIG_DIR.mkdir(parents=True, exist_ok=True)
    mode = args.mode
    base_url = args.api_base_url or (
        DEFAULT_MOCK_BASE_URL if mode == "mock" else DEFAULT_PROD_BASE_URL
    )
    text = "\n".join([
        "# Generated by scripts/devrig.py",
        f"export LOGION_DEVRIG_MODE={mode}",
        f"export LOGION_BASE_URL={base_url}",
        f"export LOGION_API_BASE_URL={base_url}",
        f"export LOGION_COMPANION_BUNDLE_SOURCE={COMPANION_SOURCE}",
        f"export LOGION_DEVRIG_ROLE={args.role}",
        "",
    ])
    path = Path(args.write)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    _emit(str(path))
    _emit(f"mode={mode}")
    _emit(f"base_url={base_url}")
    return 0


def cmd_doctor(args: argparse.Namespace) -> int:
    env = _load_env(Path(args.env_file))
    agent = args.agent
    binary = HARNESS_MAP[agent]["binary"]
    env_status = "present" if Path(args.env_file).is_file() else "missing"
    _emit(f"devrig_env: {args.env_file} ({env_status})")
    _emit(f"mode: {env.get('LOGION_DEVRIG_MODE', '<unset>')}")
    _emit(f"base_url: {env.get('LOGION_BASE_URL', '<unset>')}")
    source_status = "present" if COMPANION_SOURCE.is_dir() else "missing"
    _emit(f"companion_source: {COMPANION_SOURCE} ({source_status})")
    _emit(f"agent: {agent}")
    _emit(f"agent_binary: {binary} -> {shutil.which(binary) or '<missing>'}")
    pid_path = ROOT / ".prism.pid"
    running = False
    if pid_path.is_file():
        try:
            pid = int(pid_path.read_text(encoding="utf-8").strip())
            os.kill(pid, 0)
            running = True
        except Exception:
            running = False
    _emit(f"mock_server_running: {'yes' if running else 'no'}")
    return 0


def _install_companion(agent: str) -> int:
    skill_dir = _harness_skill_dir(agent)
    cmd = [
        "uv",
        "run",
        "logion",
        "skills",
        "install",
        "--source",
        str(COMPANION_SOURCE),
        "--course-id",
        "logion-marketplace-companion",
        "--version-id",
        _companion_version(),
        "--install-source",
        "manual",
        "--force",
        "--symlink-dir",
        str(skill_dir),
    ]
    return subprocess.run(cmd, cwd=str(ROOT), check=False).returncode


def cmd_companion(args: argparse.Namespace) -> int:
    env_path = Path(args.env_file)
    if not env_path.is_file():
        _emit(
            f"Missing env file: {env_path}. "
            "Run make dev-up MODE=mock|prod first."
        )
        return 1
    rc = _install_companion(args.agent)
    if rc != 0:
        return rc
    env = _load_env(env_path)
    _emit(f"Companion synced for agent={args.agent} role={args.role}")
    _emit(
        f"mode={env.get('LOGION_DEVRIG_MODE')} "
        f"base_url={env.get('LOGION_BASE_URL')}"
    )
    _emit(
        f"Open your harness in {ROOT} and use /logion "
        "to test against the current build."
    )
    return 0


def cmd_launch(args: argparse.Namespace) -> int:
    rc = cmd_companion(args)
    if rc != 0:
        return rc
    binary = HARNESS_MAP[args.agent]["binary"]
    resolved = shutil.which(binary)
    if resolved is None:
        _emit(f"Harness binary not found on PATH: {binary}")
        return 1
    env = os.environ.copy()
    env.update(_load_env(Path(args.env_file)))
    return subprocess.run(
        [resolved],
        cwd=str(ROOT),
        env=env,
        check=False,
    ).returncode


def cmd_clean(_args: argparse.Namespace) -> int:
    removed = 0
    for agent in HARNESS_MAP:
        link = _harness_skill_dir(agent) / "logion"
        if link.exists() or link.is_symlink():
            if link.is_dir() and not link.is_symlink():
                shutil.rmtree(link)
            else:
                link.unlink()
            removed += 1
    noun = "location" if removed == 1 else "locations"
    _emit(f"Removed {removed} companion skill {noun}")
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser()
    sub = parser.add_subparsers(dest="cmd", required=True)

    p = sub.add_parser("bootstrap")
    p.set_defaults(func=cmd_bootstrap)

    p = sub.add_parser("env")
    p.add_argument("--mode", choices=["mock", "prod"], required=True)
    p.add_argument("--api-base-url", default=None)
    p.add_argument("--role", default="seller")
    p.add_argument("--write", default=str(DEVRIG_ENV))
    p.set_defaults(func=cmd_env)

    p = sub.add_parser("doctor")
    p.add_argument("--env-file", default=str(DEVRIG_ENV))
    p.add_argument("--agent", choices=sorted(HARNESS_MAP), default="codex")
    p.set_defaults(func=cmd_doctor)

    for name, func in [("companion", cmd_companion), ("launch", cmd_launch)]:
        p = sub.add_parser(name)
        p.add_argument("--env-file", default=str(DEVRIG_ENV))
        p.add_argument("--agent", choices=sorted(HARNESS_MAP), default="codex")
        p.add_argument("--role", default="seller")
        p.set_defaults(func=func)

    p = sub.add_parser("clean")
    p.set_defaults(func=cmd_clean)
    return parser


if __name__ == "__main__":
    parser = build_parser()
    args = parser.parse_args()
    raise SystemExit(args.func(args))
