# SPDX-License-Identifier: MIT
"""Generate the CLI command reference from the argparse tree.

The reference is the mechanical half of the documentation: command tree,
flags, choices, defaults, help strings. It is derived from
``build_parser()`` so a new command or flag cannot ship undocumented, and
a documented flag cannot outlive its removal.

The other half — when to use a command, when *not* to, what a consent
mode means — is written by hand in ``docs/marketplace/``. Do not move
prose here; it will be overwritten.

Usage:
  python packages/cli/scripts/generate_reference.py           # write
  python packages/cli/scripts/generate_reference.py --check   # verify
"""

from __future__ import annotations

import argparse
import os
import sys
from collections.abc import Iterator
from contextlib import contextmanager
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[3]
TARGET = REPO_ROOT / "docs" / "reference" / "cli.md"

HEADER = """---
summary: Every Logion CLI command, flag, and default, from the parser.
---
<!-- Generated by packages/cli/scripts/generate_reference.py. Do not edit.
     Run `make docs-reference` after changing the CLI parser. -->
# CLI Reference

Mechanically derived from the argument parser, so it cannot drift from the
commands that actually exist. Conceptual guidance — when to reach for a
command, when not to, and what the consent modes mean — lives in the
hand-written articles under `docs/marketplace/`.
"""


@contextmanager
def _admin_enabled() -> Iterator[None]:
    """Expose admin commands so the reference is env-independent."""
    old = os.environ.get("LOGION_ENABLE_ADMIN")
    os.environ["LOGION_ENABLE_ADMIN"] = "1"
    try:
        yield
    finally:
        if old is None:
            os.environ.pop("LOGION_ENABLE_ADMIN", None)
        else:
            os.environ["LOGION_ENABLE_ADMIN"] = old


def _subparsers_action(
    parser: argparse.ArgumentParser,
) -> argparse._SubParsersAction | None:
    for action in parser._actions:
        if isinstance(action, argparse._SubParsersAction):
            return action
    return None


def _common_option_flags() -> frozenset[str]:
    """Flags every SDK-backed leaf inherits from ``COMMON_PARSER``.

    Repeating them under all ~150 leaves would triple the document and
    bury the flags that actually differ. They get one section instead.
    """
    from cli._options import COMMON_PARSER

    return frozenset(
        flag
        for action in COMMON_PARSER._actions
        for flag in action.option_strings
    )


def _subcommand_help(
    sub: argparse._SubParsersAction,
) -> dict[str, str]:
    """Map subcommand name to the help text registered on the parent.

    ``add_parser(name, help=...)`` stores the description on the parent's
    choice entry, not on the child parser, so a leaf's own
    ``description`` is usually empty.
    """
    return {
        choice.dest: (choice.help or "").strip()
        for choice in sub._choices_actions
    }


def _is_documented(action: argparse.Action) -> bool:
    """Skip help/version plumbing and explicitly suppressed options."""
    if action.help == argparse.SUPPRESS:
        return False
    return not isinstance(
        action, argparse._HelpAction | argparse._VersionAction
    )


def _render_choices(action: argparse.Action) -> str:
    if not action.choices:
        return ""
    rendered = ", ".join(f"`{choice}`" for choice in action.choices)
    return f" Choices: {rendered}."


def _render_default(action: argparse.Action) -> str:
    default = action.default
    if default in (None, False, argparse.SUPPRESS):
        return ""
    if default == [] or default == {}:
        return ""
    return f" Default: `{default}`."


def _render_option(action: argparse.Action) -> str:
    flags = ", ".join(f"`{opt}`" for opt in action.option_strings)
    required = " **required**" if action.required else ""
    help_text = (action.help or "").strip()
    detail = f"{help_text}" if help_text else ""
    suffix = f"{_render_choices(action)}{_render_default(action)}"
    body = " — ".join(part for part in (detail,) if part)
    line = f"- {flags}{required}"
    if body:
        line += f" — {body}"
    return line + suffix


def _render_positional(action: argparse.Action) -> str:
    name = action.metavar or action.dest
    help_text = (action.help or "").strip()
    line = f"- `{name}`"
    if help_text:
        line += f" — {help_text}"
    return line + _render_choices(action)


def _render_leaf(
    path: tuple[str, ...],
    parser: argparse.ArgumentParser,
    summary: str,
    common: frozenset[str],
) -> str:
    lines = [f"#### `logion {' '.join(path)}`", ""]
    description = summary or (parser.description or "").strip()
    if description:
        lines.extend([description, ""])

    documented = [a for a in parser._actions if _is_documented(a)]
    positionals = [a for a in documented if not a.option_strings]
    options = [
        a
        for a in documented
        if a.option_strings and not common.issuperset(a.option_strings)
    ]

    if positionals:
        lines.append("Arguments:")
        lines.append("")
        lines.extend(_render_positional(a) for a in positionals)
        lines.append("")
    if options:
        lines.append("Options:")
        lines.append("")
        lines.extend(_render_option(a) for a in options)
        lines.append("")
    return "\n".join(lines)


def _walk(
    parser: argparse.ArgumentParser,
    prefix: tuple[str, ...] = (),
    summary: str = "",
) -> Iterator[tuple[tuple[str, ...], argparse.ArgumentParser, str]]:
    sub = _subparsers_action(parser)
    if sub is None:
        yield prefix, parser, summary
        return
    helps = _subcommand_help(sub)
    for name, child in sub.choices.items():
        yield from _walk(child, (*prefix, name), helps.get(name, ""))


def _render_common_options() -> str:
    """One section for the flags shared by every SDK-backed command."""
    from cli._options import COMMON_PARSER

    lines = [
        "\n## Common options\n",
        "Accepted by every command that talks to the API.\n",
    ]
    for action in COMMON_PARSER._actions:
        if _is_documented(action) and action.option_strings:
            lines.append(_render_option(action))
    return "\n".join(lines) + "\n"


def render() -> str:
    """Render the full reference document."""
    with _admin_enabled():
        from cli._parser import build_parser

        root = build_parser()
        top = _subparsers_action(root)
        sections: list[str] = [HEADER]
        if top is None:  # pragma: no cover - the CLI always has subcommands
            return HEADER
        common = _common_option_flags()
        sections.append(_render_common_options())
        group_help = _subcommand_help(top)
        for group_name, group_parser in sorted(top.choices.items()):
            sections.append(f"\n## `{group_name}`\n")
            summary = group_help.get(group_name, "")
            if summary:
                sections.append(f"{summary}\n")
            for path, leaf, leaf_help in _walk(group_parser, (group_name,)):
                sections.append(_render_leaf(path, leaf, leaf_help, common))
    return "\n".join(sections).rstrip("\n") + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero when the committed reference is stale.",
    )
    args = parser.parse_args()

    expected = render()
    if args.check:
        current = (
            TARGET.read_text(encoding="utf-8") if TARGET.is_file() else ""
        )
        if current != expected:
            print(
                "CLI reference is stale. Run `make docs-reference`.",
                file=sys.stderr,
            )
            return 1
        print("check_cli_reference: ok.")
        return 0

    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(expected, encoding="utf-8")
    print(f"wrote {TARGET.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
